name: Upload Files to FileTransfer.io

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Upload files to FileTransfer.io
          run: |
          find . -type f -size -100M -print0 | while IFS= read -r -d '' file; do
            echo "Checking $file..."
            if [ -f "$file" ]; then
              echo "Uploading $file..."
              response=$(curl -F "file=@$file" https://file.io)
              echo "$file -> $response"
            else
              echo "Error: $file does not exist or cannot be read."
            fi
