name: Upload Files to Transfer.sh

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Upload files to Transfer.sh
        run: |
          for file in $(find . -type f -size -100M); do
            echo "Uploading $file..."
            response=$(curl --upload-file "$file" https://transfer.sh/$(basename "$file"))
            echo "$file -> $response"
          done
